version: '3'
services:
  swish:
    build: ./swish
    container_name: swish
    tty: true
    stdin_open: true
    volumes:
      - ./swish:/app
      - /app/target
    ports:
      - "3000:3000"
  cassandra:
    build: ./cassandra
    container_name: cassandra
    tty: true
    stdin_open: true
    volumes:
      - ./cassandra:/app
    ports:
      - "9042:9042"